### ISSUE TITLE
when open source code, thanks

### ISSUE THREAD

**Issue by JasonDu1993** [fuenwang/MixFairFace#1]
Thanks for contributing to open source. Your work is great.When does you plan to release the source code? Thank you!

**Comment by fuenwang** [comment]
Hi, thanks for your interest in our work. Since I am currently quite busy, I will try to release it before March. If you really need it now, you could leave your email here. I could send you my current "pre-release" version next week.

**Comment by JasonDu1993** [comment]
my email is ***@***.***，thanks again



---Original---
From: "Fu-En ***@***.***&gt;
Date: Sat, Feb 11, 2023 01:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fuenwang/MixFairFace] when open source code, thanks (Issue #1)




 
Hi, thanks for your interest in our work. Since I am currently quite busy, I will try to release it before March. If you really need it now, you could leave your email here. I could send you my current "pre-release" version next week.

**Comment by fuenwang** [comment]
@JasonDu1993 It seems that github will block email address. Maybe you can send a message to me directly via email, which is listed on my profile.

**Comment by fuenwang** [comment]
Release now
